
# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.1

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/